export const CATEGORIES = [
  {
    id: 'welfare',
    label: 'Money & Benefits',
    description: "Weekly payments, emergency cash, child benefit, carer's, and tax refunds many people are owed.",
    colour: 'text-[#16a34a]',
    bg: 'bg-[#1a2e1a]',
    icon: 'banknote',
    resources: [
      {
        name: 'Additional Needs Payment',
        desc: 'Once-off or recurring cash for costs you cannot cover — funeral expenses, moving costs, school uniforms, bedding, appliances. Almost no one knows this exists. Assessed case by case by a Community Welfare Officer with no strict income cut-off.',
        url: 'https://www.gov.ie/en/service/additional-needs-payment',
        phone: null,
        tags: ['emergency', 'cash', 'hidden-gem'],
        underused: true,
      },
      {
        name: 'Department of Social Protection (DSP)',
        desc: "Apply for Jobseeker's Allowance (€254/wk), One-Parent Family Payment, Disability Allowance, Carer's Allowance (€270/wk), Supplementary Welfare Allowance, and Child Benefit (€140/month per child).",
        url: 'https://www.gov.ie/en/organisation/department-of-social-protection',
        phone: '0818 66 22 44',
        tags: ['jobseeker', 'child-benefit', 'carer', 'disability'],
      },
      {
        name: "Carer's Allowance",
        desc: "€270/week if you care full-time for a family member. From July 2026 the income disregard rises from €625 to €1,000/week — many more families will qualify. African carers rarely claim this because caring is seen as a family duty, not an entitlement.",
        url: 'https://www.citizensinformation.ie/en/social-welfare/carers/carers-allowance/',
        phone: '0818 66 22 44',
        tags: ['carer', 'weekly-payment', 'family'],
        underused: true,
      },
      {
        name: 'Disability Allowance',
        desc: '€254/week for any disability expected to last at least 1 year. Mental health conditions (depression, anxiety, PTSD) qualify. Disability is heavily stigmatised in some African communities — this means many eligible people never apply.',
        url: 'https://www.citizensinformation.ie/en/social-welfare/disability-and-illness/disability-allowance/',
        phone: '0818 66 22 44',
        tags: ['disability', 'mental-health', 'weekly-payment'],
        underused: true,
      },
      {
        name: 'MABS — Money Advice and Budgeting Service',
        desc: 'Free, confidential help with debt, creditors, and budgeting. Will not judge you. Can negotiate directly with creditors on your behalf.',
        url: 'https://www.mabs.ie',
        phone: '0818 07 2000',
        tags: ['debt', 'budget', 'free', 'confidential'],
      },
      {
        name: 'Revenue — Rent Tax Credit & Refunds',
        desc: 'Private renters are owed up to €1,000 per year tax credit (€2,000 for couples) — backdated to 2022. Most African renters have never claimed this. Also check for overpaid PAYE and USC refunds going back 4 years.',
        url: 'https://www.revenue.ie/en/myaccount',
        phone: null,
        tags: ['tax', 'refund', 'rent-credit', 'paye'],
        underused: true,
      },
      {
        name: 'Intreo — Welfare & Employment Services',
        desc: 'Your local Intreo office handles all DSP applications, emergency payments via Community Welfare Officer, and job activation supports. Walk in or book online. Bring your PPS number and photo ID.',
        url: 'https://www.gov.ie/en/service/40cf48-find-your-local-intreo-office/',
        phone: '0818 40 7070',
        tags: ['jobseeker', 'training', 'sign-on', 'emergency'],
      },
    ],
    guides: [
      {
        title: 'How to claim the Rent Tax Credit (up to €4,000 backdated)',
        steps: [
          'Create or log in to your Revenue myAccount at revenue.ie/en/myaccount — you need your PPS number and MyGovID or manual registration',
          'Go to "PAYE Services" → "Review your tax" → select each year from 2022 onwards',
          'Click "Add credits" and search for "Rent Tax Credit"',
          'Enter the amount of rent you paid that year — you can claim 20% of the rent up to the €1,000 maximum',
          'Submit — Revenue will process within 5 working days and refund overpaid tax directly to your bank account',
          'Repeat for each year back to 2022; you can only go back 4 complete tax years from the current year',
        ],
      },
      {
        title: "What is the Additional Needs Payment and how do I get it?",
        steps: [
          'The Additional Needs Payment is a grant from the Community Welfare Service (CWO) for essential expenses you cannot cover — e.g. funeral costs, moving costs, a broken cooker, school uniforms, rent deposits, or medical equipment',
          'There is no hard income limit — it is assessed on your circumstances by the CWO',
          'Find your local Community Welfare Service by calling Intreo on 0818 40 7070 or searching gov.ie for your county Intreo office',
          'You can apply in person or by post; explain your situation clearly in writing if applying by post',
          'Bring: PPS number, recent bank statements, receipts or quotes for the item you need, any relevant letters (eviction notice, hospital letter, school letter)',
          'Decisions are usually made within 1–2 weeks; urgent cases can be same day',
        ],
      },
      {
        title: 'How to claim unpaid PAYE tax credits (up to 4 years back)',
        steps: [
          'Log in to Revenue myAccount at revenue.ie/en/myaccount',
          'Every PAYE worker is automatically entitled to the Employee Tax Credit (€2,000/year) and Personal Tax Credit (€2,000/year) — but other credits often go unclaimed',
          'Go to "Review your tax" → select the year you want to check',
          'Add any credits you are entitled to: Rent Tax Credit; Single Person Child Carer Credit (€1,900 for lone parents); Home Carer Credit (€1,950 if your partner cares at home); Tuition Fees Relief',
          'If you worked part of the year only or changed jobs, you may have overpaid tax — Revenue will show any refund due',
          'Refunds are paid directly to your bank account within a few working days',
        ],
      },
    ],
  },
  {
    id: 'housing',
    label: 'Housing',
    description: 'Tenant rights, HAP, deposit disputes, emergency accommodation, and what to do if a landlord discriminates.',
    colour: 'text-blue-400',
    bg: 'bg-blue-950',
    icon: 'home',
    resources: [
      {
        name: 'Threshold — Tenants Rights',
        desc: 'Free housing advice and advocacy. Specialists in illegal evictions, rent increases, substandard conditions, and landlords refusing HAP. Refusing HAP is illegal discrimination under the Equal Status Acts.',
        url: 'https://www.threshold.ie',
        phone: '1800 454 454',
        tags: ['tenant', 'eviction', 'repairs', 'free', 'hap'],
      },
      {
        name: 'Residential Tenancies Board (RTB)',
        desc: 'Register your tenancy, resolve disputes with landlords, and understand your legal rights. RTB also processes complaints if your landlord refuses to give back your deposit.',
        url: 'https://www.rtb.ie',
        phone: '0818 30 30 37',
        tags: ['tenancy', 'dispute', 'deposit', 'landlord'],
      },
      {
        name: 'Housing Assistance Payment (HAP)',
        desc: 'Government pays your rent directly to a private landlord — you pay a smaller contribution back to the council (means-tested). You stay on the social housing list. Dublin 2026 limit: ~€1,250/month single person; higher with 20% discretion uplift.',
        url: 'https://www.citizensinformation.ie/en/housing/renting-a-home/help-with-renting/housing-assistance-payment/',
        phone: null,
        tags: ['rent-subsidy', 'social-housing', 'council', 'hap'],
      },
      {
        name: 'Focus Ireland',
        desc: 'Support for people at risk of homelessness or in emergency accommodation. Also provides housing advice and advocacy. Freephone from any phone.',
        url: 'https://www.focusireland.ie',
        phone: '01 881 5900',
        tags: ['homelessness', 'emergency', 'support'],
      },
      {
        name: 'Social Housing — Local Authority',
        desc: 'Apply to your local council to go on the social housing list. You must have a long-term right to remain in Ireland (Stamp 4 or above generally qualifies). Processing of applications typically takes 12 weeks.',
        url: 'https://www.housingagency.ie/housing-information/social-housing-eligibility-and-need',
        phone: null,
        tags: ['social-housing', 'council', 'long-term'],
      },
      {
        name: 'Dublin Region Homeless Executive (DRHE)',
        desc: 'For anyone homeless or at risk of homelessness in Dublin. Freephone available 24/7. If you are outside Dublin, contact your local council housing department.',
        url: 'https://www.homelessdublin.ie',
        phone: '1800 707 707',
        tags: ['homeless', 'emergency', 'dublin'],
      },
    ],
    guides: [
      {
        title: 'How to apply for HAP (Housing Assistance Payment)',
        steps: [
          'You must first be on the social housing waiting list — apply at your local council office if you are not already',
          'Find a private landlord willing to accept HAP (always confirm this before signing any lease; refusing HAP is illegal discrimination)',
          'Collect the HAP application form from your local council housing office or download it from your council website',
          'Both you and your landlord complete your respective sections; the council then pays the landlord directly each month',
          'You pay a weekly rent contribution to the council — this is means-tested and is usually well below market rent',
          'Register the tenancy with the RTB within one month of moving in',
          'You remain on the social housing list while on HAP — HAP does not remove your place on the list',
        ],
      },
      {
        title: 'What to do if a landlord refuses your HAP or discriminates against you',
        steps: [
          'Refusing HAP is illegal discrimination under the Equal Status Acts (Housing Assistance ground) — this includes advertisements saying "No HAP"',
          'Gather evidence: screenshot the listing, keep emails, record dates and names of phone calls',
          'Within 2 months of the discrimination, send the landlord a Form ES.1 (available at workplacerelations.ie) — this is a required first step before a formal complaint',
          'If the landlord does not respond or discriminate again within 1 month, file a formal complaint with the WRC at workplacerelations.ie',
          'Contact Threshold (1800 454 454) for advice and help preparing your case',
          'IHREC can also bring cases in its own name where the individual cannot — contact ihrec.ie',
        ],
      },
    ],
  },
  {
    id: 'health',
    label: 'Healthcare',
    description: 'Medical cards, free GP, PRSI dental and optical benefits, mental health, and maternity care.',
    colour: 'text-red-400',
    bg: 'bg-red-950',
    icon: 'heart',
    resources: [
      {
        name: 'Medical Card / GP Visit Card',
        desc: 'Most people calculate their gross income and wrongly assume they earn too much. The assessment uses NET income after deductions (rent, childcare, travel). Many African families qualify but have never applied. GP Visit Card: single person up to €768 net/week. Free GP for all children under 8.',
        url: 'https://www.mymedicalcard.ie',
        phone: '0818 22 44 78',
        tags: ['gp', 'free', 'income-tested'],
        underused: true,
      },
      {
        name: 'PRSI Treatment Benefit — Free Dental & Optical',
        desc: 'If you pay PRSI Class A (most employees), you are entitled to a free annual dental check-up, scale and polish, free eye test, and up to €500 per hearing aid every 4 years. Almost no one in the African community knows this. Check eligibility at mywelfare.ie — you need 260 PRSI contributions.',
        url: 'https://www.gov.ie/en/service/treatment-benefit-scheme',
        phone: null,
        tags: ['dental', 'optical', 'hearing', 'prsi', 'free'],
        underused: true,
      },
      {
        name: 'HSE — Health Service Executive',
        desc: 'Access all public health services, find your nearest GP, hospital appointments, and community health supports. If you have a Medical Card, most services are free.',
        url: 'https://www.hse.ie',
        phone: '1800 700 700',
        tags: ['gp', 'hospital', 'mental-health', 'general'],
      },
      {
        name: 'Cairde — Ethnic Minority Health Organisation',
        desc: 'Specifically supports African and other ethnic minority communities to access Irish health services. Health advocacy, information in multiple languages, guidance on Medical Card applications, and referrals to culturally sensitive providers.',
        url: 'https://cairde.ie',
        phone: null,
        tags: ['african', 'community', 'health', 'advocacy', 'dublin'],
      },
      {
        name: 'Spirasi — Survivors of Torture',
        desc: 'Ireland\'s specialist service for survivors of torture, persecution, and trauma. Provides therapy, group support, English classes, and medical reports for International Protection cases. Free, confidential, respectful.',
        url: 'https://spirasi.ie',
        phone: null,
        tags: ['mental-health', 'trauma', 'torture', 'refugees', 'free'],
      },
      {
        name: 'Pieta House',
        desc: 'Free therapy and support for people affected by suicide or self-harm. 24/7 crisis line. No referral needed.',
        url: 'https://www.pieta.ie',
        phone: '116 123',
        tags: ['mental-health', 'crisis', 'free', 'suicide'],
      },
      {
        name: 'MyMind — Affordable Counselling',
        desc: 'Sliding-scale counselling starting from €25. Locations in Dublin, Cork, and Limerick, plus online. Can filter by therapist background and language. No long waiting list.',
        url: 'https://mymind.org',
        phone: null,
        tags: ['mental-health', 'affordable', 'counselling'],
      },
      {
        name: 'Text Crisis Line (free)',
        desc: 'Text HELLO to 50808. Free, 24/7 crisis text line — trained volunteers. Good for people who find it hard to talk. Available in English.',
        url: 'https://text50808.ie',
        phone: null,
        tags: ['mental-health', 'crisis', 'free', 'text'],
      },
      {
        name: 'African Mental Health Ireland',
        desc: 'Culturally sensitive mental health support specifically for African communities in Ireland.',
        url: 'https://www.africanmentalhealth.ie',
        phone: null,
        tags: ['mental-health', 'african', 'community', 'culturally-sensitive'],
      },
    ],
    guides: [
      {
        title: 'How to apply for a Medical Card (net income is what counts)',
        steps: [
          'Do NOT calculate your gross income — the HSE uses NET income after deductions: rent/mortgage, childcare costs, travel to work, and other allowable expenses',
          'Use the income calculator at mymedicalcard.ie to see if you are below the threshold before you apply',
          'Apply online at mymedicalcard.ie (fastest) — you need your PPS number and your GP\'s GMS number',
          'Gather: PPS numbers for all family members, payslips or social welfare letters showing income, proof of address, and all expense receipts/bills',
          'Non-EU nationals must also provide your IRP card',
          'Processing takes 4–6 weeks. If you have an urgent medical situation, ask specifically for an Emergency Medical Card — these can be issued within 24 hours',
          'If refused, you have 21 days to appeal — contact FLAC (01) 906 1010 for help with appeals',
        ],
      },
      {
        title: 'How to claim your free PRSI dental and optical benefit',
        steps: [
          'Go to mywelfare.ie and log in with your MyGovID (or register) — check your PRSI contribution record under "Statement of Contributions"',
          'You need at least 260 paid PRSI contributions (Class A, E, P, H, or S) if you are 29 or older; fewer contributions required if under 29',
          'Find a dentist or optician who is registered with the Treatment Benefit Scheme — they will have a sign in their window or you can search on gov.ie',
          'Tell them you are claiming Treatment Benefit — they will check your eligibility online',
          'Dental: annual exam and scale/polish are fully covered at no charge',
          'Optical: free eye test; fixed contribution toward the cost of glasses every 2 years',
          'Hearing: up to €500 per hearing aid (€1,000 for a pair) every 4 years',
          'You do NOT need to pre-approve or complete any paperwork — the dentist/optician claims directly from DSP',
        ],
      },
    ],
  },
  {
    id: 'employment',
    label: 'Work Rights',
    description: 'Minimum wage, sick pay, redundancy, permit rights, and what to do if your employer exploits you.',
    colour: 'text-orange-400',
    bg: 'bg-orange-950',
    icon: 'briefcase',
    resources: [
      {
        name: 'Workplace Relations Commission (WRC)',
        desc: 'File complaints about unpaid wages, dismissal, discrimination, or contract violations. Free, no solicitor needed. Complaints from undocumented workers are handled confidentially — WRC does not report your immigration status to the authorities.',
        url: 'https://www.workplacerelations.ie',
        phone: '0818 80 80 90',
        tags: ['complaints', 'wages', 'dismissal', 'discrimination', 'free'],
      },
      {
        name: 'Minimum Wage & Core Rights (2026)',
        desc: 'National minimum wage is €14.15/hour from January 2026. Applies to ALL workers including migrants and undocumented workers. Employers cannot deduct employment permit application fees from wages — this is illegal under the Employment Permits Act 2024.',
        url: 'https://www.citizensinformation.ie/en/employment/employment-rights-and-conditions/pay-and-employment/minimum-wage/',
        phone: null,
        tags: ['minimum-wage', 'rights', 'wages', 'permits'],
        underused: true,
      },
      {
        name: 'MRCI — Migrant Rights Centre Ireland',
        desc: 'Specialist support for migrant workers facing exploitation, trafficking, or unlawful conditions. Specific programmes for domestic workers, agricultural workers, and restaurant/hospitality workers. Operate a confidential undocumented worker service.',
        url: 'https://www.mrci.ie',
        phone: '01 889 7570',
        tags: ['exploitation', 'migrant', 'domestic', 'agriculture', 'trafficking'],
      },
      {
        name: 'Statutory Sick Pay & Redundancy',
        desc: 'You are entitled to 5 days paid sick leave per year (70% of daily wage, max €110/day) after 13 weeks employment. Statutory redundancy = 2 weeks gross pay per year of service + 1 bonus week. Redundancy is entirely TAX FREE.',
        url: 'https://www.citizensinformation.ie/en/employment/unemployment-and-redundancy/redundancy/redundancy-payments/',
        phone: null,
        tags: ['sick-pay', 'redundancy', 'tax-free', 'rights'],
        underused: true,
      },
      {
        name: 'Employment Permits — Know Your Rights',
        desc: 'Critical Skills Employment Permit (CSEP) min salary €40,904; after 2 years leads to Stamp 4. General Employment Permit: can change employer after 9 months. Reactivation Employment Permit: pathway back to legal work for those who fell out of the system through exploitation.',
        url: 'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/',
        phone: null,
        tags: ['permit', 'csep', 'stamp4', 'reactivation'],
      },
      {
        name: 'Unions — SIPTU, UNITE, FORSA',
        desc: "Trade unions protect workers through collective bargaining. Joining costs a few euros per week. SIPTU is Ireland's largest and covers most sectors. UNITE covers manufacturing and services. FORSA covers public sector.",
        url: 'https://www.siptu.ie',
        phone: '01 858 6300',
        tags: ['union', 'collective', 'protection'],
      },
    ],
    guides: [
      {
        title: 'What to do if your employer is not paying you correctly',
        steps: [
          'Document everything: keep payslips, bank statements, your contract, and any WhatsApp/email messages about pay. Note exact dates and amounts owed.',
          'Raise it internally first in writing — email your employer or HR and keep a copy of everything you send',
          'If unresolved, file a free online complaint with the WRC at workplacerelations.ie — select "Payment of Wages Act" or "National Minimum Wage Act"',
          'If you are undocumented, you can still file a WRC complaint — WRC does NOT share your immigration status with immigration authorities',
          'A WRC inspector may investigate, or the case goes to adjudication (like a small court hearing)',
          'You can be awarded up to 104 weeks wages in unpaid wages cases',
          'Contact MRCI (01 889 7570) or FLAC for help preparing your case',
        ],
      },
      {
        title: 'What to do if your employer is exploiting you (domestic/agricultural/undocumented)',
        steps: [
          'Contact MRCI immediately on 01 889 7570 — they operate a confidential service for exploited workers regardless of your immigration status',
          'If you are in danger right now, call the Garda on 999',
          'The Reactivation Employment Permit exists specifically for workers who fell out of legal work through exploitation — MRCI can advise if you qualify',
          'You have rights to all unpaid wages regardless of your immigration status — file a WRC complaint',
          'Employers cannot confiscate your passport or documents — this is illegal and may constitute trafficking',
          'If your employer is threatening you with immigration enforcement, this is illegal coercion — document it and tell MRCI',
          'You cannot be deported for filing a WRC complaint; the WRC and gardaí are separate bodies',
        ],
      },
    ],
  },
  {
    id: 'education',
    label: 'Education & Training',
    description: 'Free courses, SUSI grants, studying while on welfare, and supports for refugees in education.',
    colour: 'text-purple-400',
    bg: 'bg-purple-950',
    icon: 'graduation',
    resources: [
      {
        name: 'VTOS — Free Further Education with a Payment',
        desc: 'Free accredited courses (Level 3–6) through your local ETB for unemployed people aged 21+. You keep your social welfare payment while studying. Many African adults do not know this exists. Available nationwide through Education and Training Boards.',
        url: 'https://www.etbi.ie/vtos/',
        phone: null,
        tags: ['free', 'course', 'welfare', 'etb', 'accredited'],
        underused: true,
      },
      {
        name: 'SUSI Student Grant',
        desc: 'Maintenance and fee grants for full-time higher education. If you have Stamp 4, refugee status, or Subsidiary Protection, you qualify — NOT only Irish nationals. Apply each year at susi.ie (opens April/May). Many with refugee status do not know they are eligible.',
        url: 'https://www.susi.ie',
        phone: null,
        tags: ['grant', 'university', 'stamp4', 'refugee', 'fees'],
        underused: true,
      },
      {
        name: 'Back to Education Allowance (BTEA)',
        desc: 'If you are on Jobseeker\'s, Disability Allowance, One-Parent Family Payment, or another qualifying payment, you can go to full-time education AND keep your welfare payment. 3rd level requires 9 months on welfare first; 2nd level requires 3 months. Get Case Officer approval first.',
        url: 'https://www.gov.ie/en/service/back-to-education-allowance',
        phone: '0818 66 22 44',
        tags: ['education', 'welfare', 'keep-payment', 'btea'],
        underused: true,
      },
      {
        name: 'ETB / PLC Courses',
        desc: 'Post-Leaving Certificate (PLC) one-year courses at Level 5/6 — nursing, childcare, business, computing, and more. Available through local ETB colleges. Most are free or low cost and can be combined with a SUSI fee grant.',
        url: 'https://www.etbi.ie',
        phone: null,
        tags: ['plc', 'etb', 'level5', 'level6', 'vocational'],
      },
      {
        name: 'International Protection Student Scheme (IPSS)',
        desc: 'SUSI-equivalent supports for IP applicants in further and higher education. Must have applied for IP at least 3 years before course start. New applications open each academic year — check irishrefugeecouncil.ie for deadlines.',
        url: 'https://www.irishrefugeecouncil.ie/get-help/services-support/education-programme/state-government-funding/',
        phone: null,
        tags: ['asylum', 'student', 'grant', 'ip'],
      },
    ],
    guides: [
      {
        title: 'Can I go to college and keep my welfare payment?',
        steps: [
          'Yes — the Back to Education Allowance (BTEA) lets you study full-time and keep your social welfare payment',
          'You must be on a qualifying payment: Jobseeker\'s Allowance (9 months for 3rd level, 3 months for 2nd level), Disability Allowance, One-Parent Family Payment, or other qualifying payments',
          'Speak to your Case Officer at Intreo BEFORE you start the course — you need their approval; you cannot get BTEA retrospectively',
          'Complete form BTEA1 with your Intreo Case Officer',
          'Important: If you are on BTEA you cannot also get the SUSI maintenance grant (double funding not allowed) — but you can still claim the SUSI fee grant to cover course fees',
          'Your payment continues at the same rate you are already receiving',
        ],
      },
      {
        title: 'How to apply for a SUSI student grant (Stamp 4 and refugee holders)',
        steps: [
          'Confirm your eligibility: Irish, EU/EEA/UK/Swiss nationals qualify; holders of a Refugee Declaration, Subsidiary Protection, or Stamp 4 humanitarian leave to remain also qualify',
          'You must have been resident in Ireland, EU, EEA, UK, or Switzerland for 3 out of the last 5 years',
          'Apply online at susi.ie — applications open each year in April/May for the coming academic year',
          'You will need: PPS number, proof of immigration status (IRP card, refugee declaration), proof of household income for the previous tax year, details of your college course',
          'Grant has two parts: Maintenance Grant (living costs — means-tested) and Fee Grant (course fees — wider eligibility); apply for both',
          'Processing takes 6–8 weeks; if you need the grant to register for college, submit as early as possible',
          'If refused, appeal within the timeframe stated on your decision letter — wrong decisions are common and appeals often succeed',
        ],
      },
    ],
  },
  {
    id: 'immigration',
    label: 'Immigration & Legal',
    description: 'Visas, residency, naturalisation, family reunification (updated November 2025), and free legal aid.',
    colour: 'text-[#D97706]',
    bg: 'bg-[#2A1515]',
    icon: 'passport',
    resources: [
      {
        name: 'NASC — Migrant and Refugee Rights Centre',
        desc: 'Free immigration legal casework, family reunification, citizenship, and asylum support. Cork-based but national campaigns. Also runs Connect Project for young migrants aged 14–23.',
        url: 'https://nascireland.org',
        phone: '021 427 3594',
        tags: ['immigration', 'asylum', 'free', 'cork', 'family'],
      },
      {
        name: 'Immigrant Council of Ireland',
        desc: 'Free immigration advice helpline; legal casework on family reunification, citizenship, and trafficking. Independent law centre. Helpline operates Monday, Tuesday, Thursday, Friday 10am–1pm.',
        url: 'https://www.immigrantcouncil.ie',
        phone: '01 674 0200',
        tags: ['family', 'citizenship', 'trafficking', 'legal', 'helpline'],
      },
      {
        name: 'Crosscare Migrant Project',
        desc: 'Immigration advice, welfare rights, housing, employment, and legal referrals. Specific refugee service for Stamp 4 holders and those with protection status. Dublin-based.',
        url: 'https://crosscare.ie/services/migrants-refugees-emigrants/',
        phone: '01 836 0011',
        tags: ['pps', 'practical', 'advice', 'dublin', 'stamp4'],
      },
      {
        name: 'Doras — Limerick & Mid-West',
        desc: 'Immigration advice, employment rights, housing support, and victim support for migrant women in Limerick and the mid-west. Confidential victim support helpline for women.',
        url: 'https://doras.org',
        phone: '083 008 6391',
        tags: ['limerick', 'mid-west', 'immigration', 'women', 'victim-support'],
      },
      {
        name: 'INIS — Irish Immigration Service',
        desc: 'Official government body for visas, residency permits, IRP cards, citizenship applications, and travel documents. Use the online portal irishimmigration.ie for most applications.',
        url: 'https://www.irishimmigration.ie',
        phone: '01 616 7700',
        tags: ['visa', 'residency', 'irp', 'citizenship', 'travel-document'],
      },
      {
        name: 'FLAC — Free Legal Advice Centres',
        desc: 'Free legal advice clinics through Citizens Information Centres across Ireland. Covers immigration, employment, family, and civil law. Phone line available.',
        url: 'https://www.flac.ie',
        phone: '01 906 1010',
        tags: ['legal', 'free', 'advice', 'clinics'],
      },
      {
        name: 'Legal Aid Board — Refugee Legal Service',
        desc: 'Free legal representation throughout the International Protection (asylum) process for applicants with income below €18,000. Offices in Dublin, Cork, and Galway.',
        url: 'https://www.legalaidboard.ie',
        phone: '066 947 1000',
        tags: ['refugee', 'asylum', 'free', 'legal-aid', 'ip'],
      },
    ],
    guides: [
      {
        title: 'Family reunification rules (updated November 2025) — who can sponsor',
        steps: [
          'The rules changed substantially in November 2025. Your eligibility to sponsor depends on your immigration category.',
          'Category A (Irish citizens, recognised refugees, Subsidiary Protection holders): can apply at any time. To sponsor a spouse/partner you need €40,000 cumulative gross income over the previous 3 years. Refugees: apply within 12 months of recognition for expedited processing.',
          'Category B (Critical Skills Employment Permit holders, researchers): eligible immediately for nuclear family (spouse + children under 18). Minimum €30,000 net income for 2 previous years.',
          'Category C (General Employment Permit holders, most work permits): 12-month wait before applying for nuclear family; 5-year wait for other family members. Income thresholds apply.',
          'Get help: the Immigrant Council helpline (01 674 0200) is the best first step; NASC (021 427 3594) covers the south; MRCI if there is a work exploitation dimension.',
          'Processing currently takes 12–14 months for most applications.',
        ],
      },
      {
        title: 'How to apply for Irish citizenship by naturalisation',
        steps: [
          'You must have lived legally in Ireland for at least 5 years; the year immediately before applying must be continuous (no extended absences)',
          'Check your residency record using your IRP card, stamps in your passport, and any letters from INIS',
          'Apply online at irishimmigration.ie — the non-refundable processing fee is €175',
          'Submit: valid passport, proof of address for each of the 5 years, evidence of good character (Garda vetting, letters), and your immigration permission history',
          'Processing currently takes 18–24 months. You will receive an acknowledgement letter quickly.',
          'Do not travel outside Ireland for extended periods while your application is being processed — this can reset your continuous residency',
          'Once approved, you attend a citizenship ceremony and receive your certificate of naturalisation',
        ],
      },
      {
        title: 'International Protection (asylum) — your rights from day one',
        steps: [
          'Anyone in Ireland has the right to apply for International Protection (IP) regardless of nationality or how they entered the country',
          'Apply at the International Protection Office (IPO), 79–83 Lower Mount Street, Dublin 2',
          'After 6 months waiting for an initial decision, you can apply for permission to work — apply for a Labour Market Access Permit online at irishimmigration.ie',
          'You are entitled to full HSE healthcare access including the Medical Card from arrival',
          'Children have full access to schools from day one',
          'Access free legal representation through the Refugee Legal Service (Legal Aid Board) — this covers your full IP case',
          'Spirasi (spirasi.ie) provides specialist mental health support for survivors of torture and persecution',
        ],
      },
    ],
  },
  {
    id: 'discrimination',
    label: 'Your Rights',
    description: 'Discrimination at work, in services, or housing — how to complain and what remedy you are owed.',
    colour: 'text-[#16a34a]',
    bg: 'bg-[#1a2e1a]',
    icon: 'scale',
    resources: [
      {
        name: 'Workplace Relations Commission (WRC)',
        desc: 'File complaints about workplace discrimination on grounds of race, nationality, skin colour, or ethnic origin. Free to file. 6 months from the last act of discrimination (extended to 12 months under 2025 legislation). No cap on compensation in employment equality cases.',
        url: 'https://www.workplacerelations.ie',
        phone: '0818 80 80 90',
        tags: ['discrimination', 'race', 'employment', 'free', 'complaint'],
      },
      {
        name: 'IHREC — Human Rights & Equality Commission',
        desc: 'Ireland\'s statutory body for human rights and equality. Can bring discrimination cases in its own name where it is not reasonable to expect the individual to do so. Investigates discrimination in employment, services, accommodation, and education.',
        url: 'https://www.ihrec.ie',
        phone: '01 858 9601',
        tags: ['discrimination', 'equality', 'race', 'investigation'],
      },
      {
        name: 'Office of the Ombudsman',
        desc: 'Handles complaints about unfair treatment by government departments (DSP, Revenue), local authorities, HSE hospitals, and publicly funded schools. Free. Time limit: 12 months from the decision you are complaining about.',
        url: 'https://www.ombudsman.ie',
        phone: '01 639 5600',
        tags: ['ombudsman', 'government', 'public-services', 'free'],
      },
      {
        name: 'FLAC — Free Legal Advice',
        desc: 'Advice on whether you have a discrimination case, how to file, and what to expect. Runs clinics through Citizens Information Centres. Phone line available for initial advice.',
        url: 'https://www.flac.ie',
        phone: '01 906 1010',
        tags: ['legal', 'free', 'advice', 'discrimination'],
      },
    ],
    guides: [
      {
        title: 'How to make a discrimination complaint — step by step',
        steps: [
          'Gather evidence immediately: emails, messages, screenshots, witnesses, and a written record of exactly what happened, when, and who was present',
          'For services discrimination (shop, pub, hospital, housing): first send a Form ES.1 to the person/business that discriminated. This is a required step. Download form ES.1 from workplacerelations.ie.',
          'The service provider has 42 days to respond to your ES.1. If they do not respond or the response is unsatisfactory, file a formal complaint with the WRC.',
          'For employment discrimination: you can go straight to the WRC — no ES.1 required for employment cases',
          'Time limit: 6 months from the last incident for both services and employment (up to 12 months for reasonable cause)',
          'File at workplacerelations.ie — select "Employment Equality Acts" (for work) or "Equal Status Acts" (for services/housing)',
          'Remedies under Employment Equality Acts: no cap on compensation; orders for reinstatement or changes in policy. Under Equal Status Acts: up to €15,000.',
          'FLAC (01 906 1010) or IHREC can advise you and may support your case',
        ],
      },
    ],
  },
  {
    id: 'legal',
    label: 'Legal Rights',
    description: 'Free legal advice, equality law, and step-by-step guides to taking your rights seriously.',
    colour: 'text-purple-400',
    bg: 'bg-purple-950',
    icon: 'scale',
    resources: [
      {
        name: 'FLAC — Free Legal Advice Centres',
        desc: 'Free legal advice clinics throughout Ireland through Citizens Information Centres. Covers employment, housing, family, immigration, and consumer rights. Phone line for initial advice.',
        url: 'https://www.flac.ie',
        phone: '01 906 1010',
        tags: ['free', 'advice', 'civil-legal-aid'],
      },
      {
        name: 'Citizens Information',
        desc: 'The most comprehensive guide to your rights and entitlements in Ireland — social welfare, housing, employment, health, consumer rights, and more. Available online and in person at Citizens Information Centres.',
        url: 'https://www.citizensinformation.ie',
        phone: '0818 07 4000',
        tags: ['rights', 'entitlements', 'free', 'general'],
      },
      {
        name: 'Legal Aid Board',
        desc: 'State-funded legal representation for people who cannot afford a solicitor. Means-tested (income below €18,000 for criminal legal aid; separate civil legal aid scheme). Refugee Legal Service for IP cases is separate and free.',
        url: 'https://www.legalaidboard.ie',
        phone: '066 947 1000',
        tags: ['solicitor', 'court', 'criminal', 'civil'],
      },
      {
        name: 'Workplace Relations Commission (WRC)',
        desc: 'File complaints about workplace discrimination, unfair dismissal, or unpaid wages. Free. No solicitor needed. Also handles Equal Status (services, housing, education) complaints.',
        url: 'https://www.workplacerelations.ie',
        phone: '0818 80 80 90',
        tags: ['employment', 'discrimination', 'wages', 'dismissal'],
      },
    ],
    guides: [
      {
        title: 'How to make a discrimination complaint (workplace)',
        steps: [
          'Gather evidence: emails, messages, witnesses, and a written record of every incident with dates',
          'File with the WRC within 6 months of the last act of discrimination (up to 12 months under 2025 law with reasonable cause)',
          'Go to workplacerelations.ie → "Make a Complaint" → select Employment Equality Acts',
          'FLAC (01 906 1010) or IHREC can help you prepare your case for free',
          'WRC mediators attempt resolution first; if unresolved, it goes to adjudication — similar to a court hearing but simpler',
          'There is no cap on compensation for employment discrimination cases',
        ],
      },
    ],
  },
  {
    id: 'community',
    label: 'Community Orgs',
    description: 'African and migrant community organisations offering health, welfare, women\'s, and worker support across Ireland.',
    colour: 'text-[#D97706]',
    bg: 'bg-[#2A1515]',
    icon: 'users',
    resources: [
      {
        name: 'Cairde — Ethnic Minority Health',
        desc: 'Dublin-based organisation reducing health inequalities for African and other ethnic minority communities. Health advocacy, access to services, culturally sensitive provider listings, and health literacy programmes.',
        url: 'https://cairde.ie',
        phone: null,
        tags: ['health', 'african', 'advocacy', 'dublin', 'community'],
      },
      {
        name: 'AkiDwA — Migrant Women\'s Network',
        desc: 'National network of migrant women including many African women. Works on employment, gender-based violence, FGM awareness, forced marriage, and community health. Runs training, health fairs, and advocacy campaigns.',
        url: 'https://akidwa.ie',
        phone: '01 834 9851',
        tags: ['women', 'migrant', 'african', 'health', 'gbv'],
      },
      {
        name: 'Spirasi — Torture Survivors Support',
        desc: 'Provides specialist therapy, group support, and English classes for survivors of torture, persecution, and inhumane treatment. Also prepares medical-legal reports for International Protection cases. Free and confidential.',
        url: 'https://spirasi.ie',
        phone: null,
        tags: ['trauma', 'torture', 'mental-health', 'refugees', 'dublin'],
      },
      {
        name: 'MRCI — Migrant Rights Centre',
        desc: 'Rights and advocacy for migrant workers, especially domestic workers, agricultural workers, and restaurant/hospitality workers. Undocumented worker service. Helpline, casework, and legal support.',
        url: 'https://www.mrci.ie',
        phone: '01 889 7570',
        tags: ['workers', 'domestic', 'exploitation', 'undocumented'],
      },
      {
        name: 'Doras — Limerick & Mid-West',
        desc: 'Supports migrants and ethnic minorities in Limerick and the mid-west. Immigration advice, employment rights, housing, and confidential victim support for migrant women.',
        url: 'https://doras.org',
        phone: '083 008 6391',
        tags: ['limerick', 'mid-west', 'women', 'immigration'],
      },
      {
        name: 'Black Therapists Ireland',
        desc: 'Online directory of Black therapists working in Ireland. Face-to-face and online options. Finding a therapist who understands your cultural background can make a significant difference.',
        url: 'https://blacktherapistsireland.com',
        phone: null,
        tags: ['mental-health', 'therapy', 'black', 'directory'],
      },
      {
        name: 'MyMind — Affordable Counselling',
        desc: 'Sliding-scale counselling from €25. Dublin, Cork, Limerick, and online. Filter by therapist language, background, and speciality. No long NHS-style waiting list.',
        url: 'https://mymind.org',
        phone: null,
        tags: ['counselling', 'affordable', 'sliding-scale'],
      },
    ],
    guides: [
      {
        title: 'Finding culturally sensitive mental health support in Ireland',
        steps: [
          'Your GP can refer you to the community mental health team — this is free with a Medical Card but waiting times can be long (months)',
          'For faster access to culturally sensitive support: MyMind (mymind.org) offers affordable sliding-scale counselling from €25 — you can filter therapists by background and language',
          'Black Therapists Ireland (blacktherapistsireland.com) is a directory of Black therapists working in Ireland — both face-to-face and online',
          'Spirasi (spirasi.ie) provides free specialist therapy for survivors of torture, persecution, and trauma — no referral needed',
          'African Mental Health Ireland (africanmentalhealth.ie) provides culturally sensitive support specifically for African communities',
          'In a crisis right now: text HELLO to 50808 (free, 24/7); or call Samaritans on 116 123 (free, 24/7)',
          'Cairde (cairde.ie) can help you navigate HSE mental health services and find culturally appropriate supports',
        ],
      },
    ],
  },
  {
    id: 'grants',
    label: 'Grants for Groups',
    description: 'Funding for African-led and migrant community organisations in Ireland.',
    colour: 'text-blue-400',
    bg: 'bg-blue-950',
    icon: 'trophy',
    resources: [
      {
        name: 'Ireland Against Racism Fund (IARF)',
        desc: 'Department of Justice grant for NGOs and community organisations tackling racism and promoting racial equality. Scheme A: €40,000–€100,000. Scheme B: €5,000–€10,000. 2025 round: 37 projects funded, €1.5m+ distributed. Annual deadline usually August.',
        url: 'https://www.gov.ie/en/campaigns/ireland-against-racism-fund/',
        phone: null,
        tags: ['grant', 'anti-racism', 'ngo', 'department-of-justice'],
      },
      {
        name: 'Pobal Community Services Programme (CSP)',
        desc: 'Core multi-year funding for community organisations with a social enterprise model. 2026 budget: €59.4m. African-led organisations providing community services are eligible. Applications typically open in spring.',
        url: 'https://www.pobal.ie/programmes/community-services-programme-csp/',
        phone: null,
        tags: ['pobal', 'core-funding', 'community', 'social-enterprise'],
      },
      {
        name: 'Rethink Ireland — Social Innovation Fund',
        desc: 'Supports social enterprises led by or serving migrants, refugees, and ethnic minorities. Up to €60,000/year over 3 years. Competitive application — focus on measurable social impact.',
        url: 'https://rethinkireland.ie',
        phone: null,
        tags: ['social-enterprise', 'migrants', 'innovation', 'funding'],
      },
      {
        name: 'Local Enhancement Programme — County Council Grants',
        desc: 'Most county councils run local community grants (LEP). African-led community groups in a county can apply for small grants. Contact your county council Community Development department for amounts and deadlines.',
        url: 'https://www.gov.ie/en/policy-information/local-enhancement-programme/',
        phone: null,
        tags: ['local', 'council', 'small-grant', 'community'],
      },
      {
        name: 'Scheme to Support National Organisations (SSNO)',
        desc: 'Pobal-administered multi-annual core funding for national community and voluntary organisations. Must be a registered charity or company limited by guarantee with national remit.',
        url: 'https://www.pobal.ie/programmes/scheme-to-support-national-organisations-ssno-2022-2025/',
        phone: null,
        tags: ['national', 'charity', 'core-funding', 'pobal'],
      },
    ],
    guides: [
      {
        title: 'How to apply for the Ireland Against Racism Fund',
        steps: [
          'Monitor gov.ie/en/campaigns/ireland-against-racism-fund/ for the annual call — usually opens in June with a deadline in August',
          'Decide which scheme suits your organisation: Scheme A (€40k–€100k, larger projects, 12 months) or Scheme B (€5k–€10k, smaller, targeted activity)',
          'Five thematic areas: Being Safe and Being Heard; Being Equal; Being Seen and Taking Part; Being Counted; Being Together — your project should clearly fit one',
          'Your organisation must be a registered charity, company limited by guarantee, or an established community group; individuals cannot apply',
          'Prepare: 2 years of audited accounts; Charities Regulator or Companies Registration Office number; clear project budget and outcomes; evidence of community need',
          'Ensure your application demonstrates measurable outcomes — number of people reached, events held, policy changes sought',
          'Late applications are not accepted; build in time to get sign-off from your board before submission',
        ],
      },
    ],
  },
] as const
