export const CATEGORIES = [
  {
    id: 'legal',
    label: 'Legal Rights',
    description: 'Free legal advice, equality law, and how to make complaints.',
    colour: 'text-purple-400',
    bg: 'bg-purple-950',
    icon: 'scale',
    resources: [
      {
        name: 'FLAC — Free Legal Advice Centres',
        desc: 'Free legal advice clinics throughout Ireland. Drop-in sessions, phone line, and civil legal aid referrals.',
        url: 'https://www.flac.ie',
        phone: '1800 110 110',
        tags: ['free', 'advice', 'civil-legal-aid'],
      },
      {
        name: 'Citizens Information',
        desc: 'The most comprehensive guide to your rights and entitlements in Ireland. Covers everything from social welfare to consumer rights.',
        url: 'https://www.citizensinformation.ie',
        phone: '0818 07 4000',
        tags: ['rights', 'entitlements', 'free'],
      },
      {
        name: 'Irish Human Rights & Equality Commission',
        desc: 'Investigates discrimination in employment, services, and accommodation. Free assistance for equality cases.',
        url: 'https://www.ihrec.ie',
        phone: '01 858 9601',
        tags: ['discrimination', 'equality', 'race'],
      },
      {
        name: 'Legal Aid Board',
        desc: 'State-funded legal representation for those who cannot afford a solicitor. Means-tested.',
        url: 'https://www.legalaidboard.ie',
        phone: '066 947 1000',
        tags: ['solicitor', 'court', 'criminal', 'civil'],
      },
      {
        name: 'Workplace Relations Commission (WRC)',
        desc: 'File complaints about workplace discrimination, unfair dismissal, or unpaid wages. Free to use.',
        url: 'https://www.workplacerelations.ie',
        phone: '0818 80 80 90',
        tags: ['employment', 'discrimination', 'wages', 'dismissal'],
      },
    ],
    guides: [
      {
        title: 'How to make a discrimination complaint',
        steps: [
          'Gather evidence: emails, messages, witnesses, records of incidents',
          'File with the WRC within 6 months of the last incident (12 months in exceptional cases)',
          'Go to workplacerelations.ie → "Make a Complaint" → select Equal Status or Employment Equality',
          'FLAC or IHREC can help you prepare your case for free',
          'WRC mediators will attempt resolution first. If unresolved, it proceeds to adjudication.',
        ],
      },
    ],
  },
  {
    id: 'housing',
    label: 'Housing',
    description: 'Tenant rights, HAP, deposit disputes, and homelessness support.',
    colour: 'text-blue-400',
    bg: 'bg-blue-950',
    icon: 'home',
    resources: [
      {
        name: 'Threshold',
        desc: 'Free housing advice and advocacy. Specialists in tenancy rights, illegal evictions, and substandard conditions.',
        url: 'https://www.threshold.ie',
        phone: '1800 454 454',
        tags: ['tenant', 'eviction', 'repairs', 'free'],
      },
      {
        name: 'Residential Tenancies Board (RTB)',
        desc: 'Register your tenancy, resolve disputes with landlords, and understand your rights as a tenant.',
        url: 'https://www.rtb.ie',
        phone: '0818 30 30 37',
        tags: ['tenancy', 'dispute', 'deposit', 'landlord'],
      },
      {
        name: 'Housing Assistance Payment (HAP)',
        desc: 'Government rent subsidy for those on low income or social housing lists. Apply through your local council.',
        url: 'https://www.gov.ie/en/service/e3b0c8-housing-assistance-payment',
        phone: null,
        tags: ['rent-subsidy', 'social-housing', 'council'],
      },
      {
        name: 'Focus Ireland',
        desc: 'Support services for people at risk of homelessness or in emergency accommodation.',
        url: 'https://www.focusireland.ie',
        phone: '01 881 5900',
        tags: ['homelessness', 'emergency', 'support'],
      },
    ],
    guides: [
      {
        title: 'How to apply for HAP (Housing Assistance Payment)',
        steps: [
          'You must be on the housing list — apply at your local council if you are not already',
          'Find a private landlord willing to accept HAP (confirm before signing any lease)',
          'Complete the HAP application form — available from your council office or council website',
          'Your landlord completes the landlord section; the council pays them directly each month',
          'You pay a rent contribution to the council (means-tested, usually well below market rent)',
          'Register the tenancy with the RTB within one month',
        ],
      },
    ],
  },
  {
    id: 'immigration',
    label: 'Immigration & Citizenship',
    description: 'Visas, residency, naturalisation, and family reunification.',
    colour: 'text-[#D97706]',
    bg: 'bg-[#2A1515]',
    icon: 'passport',
    resources: [
      {
        name: 'NASC — Immigrant Support Centre',
        desc: 'Free immigration advice, legal representation, and advocacy for migrants and refugees in Ireland.',
        url: 'https://nascireland.org',
        phone: '021 427 3594',
        tags: ['immigration', 'asylum', 'free', 'cork'],
      },
      {
        name: 'Immigrant Council of Ireland',
        desc: 'Legal advice on immigration, family reunification, citizenship, and trafficking. Information line available.',
        url: 'https://www.immigrantcouncil.ie',
        phone: '01 674 0202',
        tags: ['family', 'citizenship', 'trafficking', 'legal'],
      },
      {
        name: 'Migrant Rights Centre Ireland (MRCI)',
        desc: 'Rights and advocacy for migrant workers, particularly those in domestic work, agriculture, and hospitality.',
        url: 'https://www.mrci.ie',
        phone: '01 889 7570',
        tags: ['workers', 'domestic', 'exploitation', 'rights'],
      },
      {
        name: 'INIS — Irish Naturalisation & Immigration Service',
        desc: 'Official government body for visas, residency, citizenship applications, and travel documents.',
        url: 'https://www.irishimmigration.ie',
        phone: '01 616 7700',
        tags: ['visa', 'residency', 'citizenship', 'travel-document'],
      },
      {
        name: 'Crosscare Migrant Project',
        desc: 'Advice and support for migrants navigating Irish bureaucracy — PPS numbers, housing, employment, and more.',
        url: 'https://crosscare.ie/migrant-project',
        phone: '01 836 0011',
        tags: ['pps', 'practical', 'advice', 'dublin'],
      },
    ],
    guides: [
      {
        title: 'How to apply for Irish citizenship by naturalisation',
        steps: [
          'You must have lived legally in Ireland for at least 5 years (1 year immediately before applying must be continuous)',
          'Check your residency using your Irish Residence Permit (IRP) stamps and letters',
          'Apply online at irishimmigration.ie — processing fee is €175 (non-refundable)',
          'Submit supporting documents: passport, proof of address for each year, evidence of good character',
          'Processing currently takes 18–24 months. You will receive a letter acknowledging receipt.',
          'Do not travel outside Ireland for extended periods while your application is being processed',
          'Once approved, attend a citizenship ceremony — you will receive your certificate of naturalisation',
        ],
      },
    ],
  },
  {
    id: 'welfare',
    label: 'Benefits & Welfare',
    description: "Social welfare, jobseeker's, child benefit, and financial support.",
    colour: 'text-[#16a34a]',
    bg: 'bg-[#1a2e1a]',
    icon: 'shield',
    resources: [
      {
        name: 'Department of Social Protection',
        desc: "Apply for Jobseeker's Allowance, Child Benefit, Back to Education, Supplementary Welfare, and more.",
        url: 'https://www.gov.ie/en/organisation/department-of-social-protection',
        phone: '0818 66 22 44',
        tags: ['jobseeker', 'child-benefit', 'allowance'],
      },
      {
        name: 'MABS — Money Advice and Budgeting Service',
        desc: 'Free, confidential help with debt management, budgeting, and dealing with creditors.',
        url: 'https://www.mabs.ie',
        phone: '0818 07 2000',
        tags: ['debt', 'budget', 'free', 'confidential'],
      },
      {
        name: 'Intreo — Employment Services',
        desc: 'Sign on, job activation supports, and access to training schemes. Your local Intreo office is your first stop.',
        url: 'https://www.intreo.ie',
        phone: null,
        tags: ['jobseeker', 'training', 'sign-on'],
      },
      {
        name: 'Revenue — Tax Credits & Refunds',
        desc: 'Check if you are owed a tax refund, claim credits, or understand PAYE. Many immigrants are owed money back.',
        url: 'https://www.revenue.ie',
        phone: '01 738 3636',
        tags: ['tax', 'refund', 'paye', 'pps'],
      },
    ],
    guides: [
      {
        title: 'How to get your PPS Number',
        steps: [
          'A PPS (Personal Public Service) number is required to access most government services, work, and pay tax',
          'Book an appointment at your nearest Intreo or DSP office — appointments are required, walk-ins are not accepted',
          "Bring: valid passport or national identity card, proof of address (utility bill, bank letter dated within 3 months), and evidence of why you need the PPS number (e.g. employment contract, child's school letter)",
          'Non-EU nationals must also bring their Irish Residence Permit (IRP)',
          'The number is issued on the day or by post within a few days',
          'Once you have your PPS number, register for myAccount at revenue.ie to manage your taxes online',
        ],
      },
    ],
  },
  {
    id: 'employment',
    label: 'Employment Rights',
    description: 'Minimum wage, contracts, sick leave, and workplace complaints.',
    colour: 'text-orange-400',
    bg: 'bg-orange-950',
    icon: 'briefcase',
    resources: [
      {
        name: 'Workplace Relations Commission',
        desc: 'File complaints about wages, dismissal, discrimination, or contract violations. Free to use, no solicitor needed.',
        url: 'https://www.workplacerelations.ie',
        phone: '0818 80 80 90',
        tags: ['complaints', 'wages', 'dismissal', 'discrimination'],
      },
      {
        name: 'National Employment Rights Authority (NERA) Info Line',
        desc: 'Get information about your employment rights including holiday pay, minimum wage, and rest breaks.',
        url: 'https://www.workplacerelations.ie',
        phone: '0818 80 80 90',
        tags: ['rights', 'wages', 'holiday'],
      },
      {
        name: 'MRCI Workers Rights',
        desc: 'Specialist support for migrant workers facing exploitation, trafficking, or unlawful working conditions.',
        url: 'https://www.mrci.ie',
        phone: '01 889 7570',
        tags: ['exploitation', 'migrant', 'trafficking'],
      },
      {
        name: 'Unions — SIPTU, UNITE, FORSA',
        desc: "Trade unions protect workers' rights through collective bargaining. Joining a union costs a few euros per week.",
        url: 'https://www.siptu.ie',
        phone: '01 858 6300',
        tags: ['union', 'collective', 'protection'],
      },
    ],
    guides: [
      {
        title: 'What to do if your employer is not paying you correctly',
        steps: [
          'Document everything: keep payslips, bank statements, and your contract. Note dates and amounts',
          'Raise it internally first in writing — email your employer or HR and keep a copy',
          "If unresolved, file an online complaint with the WRC at workplacerelations.ie — it's free",
          'Select "Payment of Wages Act" or "National Minimum Wage Act" as the basis of your complaint',
          'A WRC inspector may investigate, or the case goes to adjudication (like a mini court)',
          'You can be awarded up to 104 weeks\' wages in unpaid wages cases',
          'Contact FLAC or MRCI if you need help preparing your case',
        ],
      },
    ],
  },
  {
    id: 'health',
    label: 'Healthcare',
    description: 'Medical cards, GP access, mental health, and HSE services.',
    colour: 'text-red-400',
    bg: 'bg-red-950',
    icon: 'heart',
    resources: [
      {
        name: 'HSE — Health Service Executive',
        desc: 'Access public health services, find your nearest GP, hospital, and mental health supports.',
        url: 'https://www.hse.ie',
        phone: '1800 700 700',
        tags: ['gp', 'hospital', 'mental-health'],
      },
      {
        name: 'Medical Card / GP Visit Card',
        desc: 'Free or subsidised GP visits if your income is below a threshold. Apply through the HSE or at mywelfare.ie.',
        url: 'https://www.citizensinformation.ie/en/health/entitlement-to-health-services/medical-card',
        phone: '0818 22 44 78',
        tags: ['gp', 'free', 'income-tested'],
      },
      {
        name: 'Pieta House',
        desc: 'Free therapy and support for people affected by suicide or self-harm. 24/7 crisis line.',
        url: 'https://www.pieta.ie',
        phone: '116 123',
        tags: ['mental-health', 'crisis', 'free', 'suicide'],
      },
      {
        name: 'African Mental Health Ireland',
        desc: 'Culturally sensitive mental health support specifically for African communities in Ireland.',
        url: 'https://www.africanmentalhealth.ie',
        phone: null,
        tags: ['mental-health', 'african', 'community', 'culturally-sensitive'],
      },
    ],
    guides: [
      {
        title: 'How to apply for a Medical Card',
        steps: [
          'Check your eligibility — income thresholds vary by age and family size. Single person under 66 earns under approx. €184/week net',
          'Apply online at mywelfare.ie (requires a MyGovID account) or by post using form MC1',
          'You will need: PPS numbers for all family members, proof of income (payslips, P60, or social welfare letter), proof of address',
          'Non-EU nationals must also provide their IRP card',
          'Processing takes 4–6 weeks. In an urgent medical situation, ask for an emergency medical card.',
          'If refused, you can appeal within 21 days — FLAC can assist with appeals',
        ],
      },
    ],
  },
] as const
