// ISO 3166-1 alpha-2 codes + display names
// African nations listed first (primary diaspora); rest alphabetical
export interface Country {
  code: string
  name: string
  nationality: string
}

export const COUNTRIES: Country[] = [
  // ── African nations (priority for diaspora platform) ──────────────────────
  { code: 'NG', name: 'Nigeria',               nationality: 'Nigerian' },
  { code: 'GH', name: 'Ghana',                 nationality: 'Ghanaian' },
  { code: 'ZA', name: 'South Africa',          nationality: 'South African' },
  { code: 'KE', name: 'Kenya',                 nationality: 'Kenyan' },
  { code: 'ET', name: 'Ethiopia',              nationality: 'Ethiopian' },
  { code: 'TZ', name: 'Tanzania',              nationality: 'Tanzanian' },
  { code: 'UG', name: 'Uganda',                nationality: 'Ugandan' },
  { code: 'CM', name: 'Cameroon',              nationality: 'Cameroonian' },
  { code: 'SN', name: 'Senegal',               nationality: 'Senegalese' },
  { code: 'CI', name: "Côte d'Ivoire",         nationality: 'Ivorian' },
  { code: 'ZW', name: 'Zimbabwe',              nationality: 'Zimbabwean' },
  { code: 'ZM', name: 'Zambia',                nationality: 'Zambian' },
  { code: 'RW', name: 'Rwanda',                nationality: 'Rwandan' },
  { code: 'SO', name: 'Somalia',               nationality: 'Somali' },
  { code: 'SD', name: 'Sudan',                 nationality: 'Sudanese' },
  { code: 'SS', name: 'South Sudan',           nationality: 'South Sudanese' },
  { code: 'EG', name: 'Egypt',                 nationality: 'Egyptian' },
  { code: 'MA', name: 'Morocco',               nationality: 'Moroccan' },
  { code: 'DZ', name: 'Algeria',               nationality: 'Algerian' },
  { code: 'TN', name: 'Tunisia',               nationality: 'Tunisian' },
  { code: 'LY', name: 'Libya',                 nationality: 'Libyan' },
  { code: 'AO', name: 'Angola',                nationality: 'Angolan' },
  { code: 'MZ', name: 'Mozambique',            nationality: 'Mozambican' },
  { code: 'MG', name: 'Madagascar',            nationality: 'Malagasy' },
  { code: 'MW', name: 'Malawi',                nationality: 'Malawian' },
  { code: 'BJ', name: 'Benin',                 nationality: 'Beninese' },
  { code: 'BF', name: 'Burkina Faso',          nationality: 'Burkinabé' },
  { code: 'ML', name: 'Mali',                  nationality: 'Malian' },
  { code: 'NE', name: 'Niger',                 nationality: 'Nigerien' },
  { code: 'TD', name: 'Chad',                  nationality: 'Chadian' },
  { code: 'GN', name: 'Guinea',                nationality: 'Guinean' },
  { code: 'GW', name: 'Guinea-Bissau',         nationality: 'Bissau-Guinean' },
  { code: 'SL', name: 'Sierra Leone',          nationality: 'Sierra Leonean' },
  { code: 'LR', name: 'Liberia',               nationality: 'Liberian' },
  { code: 'GM', name: 'Gambia',                nationality: 'Gambian' },
  { code: 'MR', name: 'Mauritania',            nationality: 'Mauritanian' },
  { code: 'ER', name: 'Eritrea',               nationality: 'Eritrean' },
  { code: 'DJ', name: 'Djibouti',              nationality: 'Djiboutian' },
  { code: 'CD', name: 'DR Congo',              nationality: 'Congolese' },
  { code: 'CG', name: 'Republic of Congo',     nationality: 'Congolese' },
  { code: 'GA', name: 'Gabon',                 nationality: 'Gabonese' },
  { code: 'GQ', name: 'Equatorial Guinea',     nationality: 'Equatorial Guinean' },
  { code: 'ST', name: 'São Tomé & Príncipe',   nationality: 'São Toméan' },
  { code: 'CV', name: 'Cape Verde',            nationality: 'Cape Verdean' },
  { code: 'MU', name: 'Mauritius',             nationality: 'Mauritian' },
  { code: 'SC', name: 'Seychelles',            nationality: 'Seychellois' },
  { code: 'KM', name: 'Comoros',               nationality: 'Comorian' },
  { code: 'NA', name: 'Namibia',               nationality: 'Namibian' },
  { code: 'BW', name: 'Botswana',              nationality: 'Batswana' },
  { code: 'LS', name: 'Lesotho',               nationality: 'Basotho' },
  { code: 'SZ', name: 'Eswatini',              nationality: 'Swazi' },
  { code: 'CF', name: 'Central African Republic', nationality: 'Central African' },
  { code: 'BI', name: 'Burundi',               nationality: 'Burundian' },
  { code: 'TG', name: 'Togo',                  nationality: 'Togolese' },
  { code: 'GH', name: 'Ghana',                 nationality: 'Ghanaian' },

  // ── Rest of world ─────────────────────────────────────────────────────────
  { code: 'AF', name: 'Afghanistan',           nationality: 'Afghan' },
  { code: 'AL', name: 'Albania',               nationality: 'Albanian' },
  { code: 'AD', name: 'Andorra',               nationality: 'Andorran' },
  { code: 'AG', name: 'Antigua & Barbuda',     nationality: 'Antiguan' },
  { code: 'AR', name: 'Argentina',             nationality: 'Argentinian' },
  { code: 'AM', name: 'Armenia',               nationality: 'Armenian' },
  { code: 'AU', name: 'Australia',             nationality: 'Australian' },
  { code: 'AT', name: 'Austria',               nationality: 'Austrian' },
  { code: 'AZ', name: 'Azerbaijan',            nationality: 'Azerbaijani' },
  { code: 'BS', name: 'Bahamas',               nationality: 'Bahamian' },
  { code: 'BH', name: 'Bahrain',               nationality: 'Bahraini' },
  { code: 'BD', name: 'Bangladesh',            nationality: 'Bangladeshi' },
  { code: 'BB', name: 'Barbados',              nationality: 'Barbadian' },
  { code: 'BY', name: 'Belarus',               nationality: 'Belarusian' },
  { code: 'BE', name: 'Belgium',               nationality: 'Belgian' },
  { code: 'BZ', name: 'Belize',                nationality: 'Belizean' },
  { code: 'BT', name: 'Bhutan',               nationality: 'Bhutanese' },
  { code: 'BO', name: 'Bolivia',               nationality: 'Bolivian' },
  { code: 'BA', name: 'Bosnia & Herzegovina',  nationality: 'Bosnian' },
  { code: 'BR', name: 'Brazil',                nationality: 'Brazilian' },
  { code: 'BN', name: 'Brunei',               nationality: 'Bruneian' },
  { code: 'BG', name: 'Bulgaria',              nationality: 'Bulgarian' },
  { code: 'KH', name: 'Cambodia',              nationality: 'Cambodian' },
  { code: 'CA', name: 'Canada',                nationality: 'Canadian' },
  { code: 'CL', name: 'Chile',                 nationality: 'Chilean' },
  { code: 'CN', name: 'China',                 nationality: 'Chinese' },
  { code: 'CO', name: 'Colombia',              nationality: 'Colombian' },
  { code: 'CR', name: 'Costa Rica',            nationality: 'Costa Rican' },
  { code: 'HR', name: 'Croatia',               nationality: 'Croatian' },
  { code: 'CU', name: 'Cuba',                  nationality: 'Cuban' },
  { code: 'CY', name: 'Cyprus',                nationality: 'Cypriot' },
  { code: 'CZ', name: 'Czech Republic',        nationality: 'Czech' },
  { code: 'DK', name: 'Denmark',               nationality: 'Danish' },
  { code: 'DM', name: 'Dominica',              nationality: 'Dominican' },
  { code: 'DO', name: 'Dominican Republic',    nationality: 'Dominican' },
  { code: 'EC', name: 'Ecuador',               nationality: 'Ecuadorean' },
  { code: 'SV', name: 'El Salvador',           nationality: 'Salvadorian' },
  { code: 'EE', name: 'Estonia',               nationality: 'Estonian' },
  { code: 'FJ', name: 'Fiji',                  nationality: 'Fijian' },
  { code: 'FI', name: 'Finland',               nationality: 'Finnish' },
  { code: 'FR', name: 'France',                nationality: 'French' },
  { code: 'GE', name: 'Georgia',               nationality: 'Georgian' },
  { code: 'DE', name: 'Germany',               nationality: 'German' },
  { code: 'GR', name: 'Greece',                nationality: 'Greek' },
  { code: 'GD', name: 'Grenada',               nationality: 'Grenadian' },
  { code: 'GT', name: 'Guatemala',             nationality: 'Guatemalan' },
  { code: 'GY', name: 'Guyana',                nationality: 'Guyanese' },
  { code: 'HT', name: 'Haiti',                 nationality: 'Haitian' },
  { code: 'HN', name: 'Honduras',              nationality: 'Honduran' },
  { code: 'HU', name: 'Hungary',               nationality: 'Hungarian' },
  { code: 'IS', name: 'Iceland',               nationality: 'Icelandic' },
  { code: 'IN', name: 'India',                 nationality: 'Indian' },
  { code: 'ID', name: 'Indonesia',             nationality: 'Indonesian' },
  { code: 'IR', name: 'Iran',                  nationality: 'Iranian' },
  { code: 'IQ', name: 'Iraq',                  nationality: 'Iraqi' },
  { code: 'IE', name: 'Ireland',               nationality: 'Irish' },
  { code: 'IL', name: 'Israel',                nationality: 'Israeli' },
  { code: 'IT', name: 'Italy',                 nationality: 'Italian' },
  { code: 'JM', name: 'Jamaica',               nationality: 'Jamaican' },
  { code: 'JP', name: 'Japan',                 nationality: 'Japanese' },
  { code: 'JO', name: 'Jordan',                nationality: 'Jordanian' },
  { code: 'KZ', name: 'Kazakhstan',            nationality: 'Kazakhstani' },
  { code: 'KW', name: 'Kuwait',                nationality: 'Kuwaiti' },
  { code: 'KG', name: 'Kyrgyzstan',            nationality: 'Kyrgyz' },
  { code: 'LA', name: 'Laos',                  nationality: 'Laotian' },
  { code: 'LV', name: 'Latvia',                nationality: 'Latvian' },
  { code: 'LB', name: 'Lebanon',               nationality: 'Lebanese' },
  { code: 'LI', name: 'Liechtenstein',         nationality: 'Liechtensteinese' },
  { code: 'LT', name: 'Lithuania',             nationality: 'Lithuanian' },
  { code: 'LU', name: 'Luxembourg',            nationality: 'Luxembourger' },
  { code: 'MK', name: 'North Macedonia',       nationality: 'Macedonian' },
  { code: 'MY', name: 'Malaysia',              nationality: 'Malaysian' },
  { code: 'MV', name: 'Maldives',              nationality: 'Maldivian' },
  { code: 'MT', name: 'Malta',                 nationality: 'Maltese' },
  { code: 'MX', name: 'Mexico',                nationality: 'Mexican' },
  { code: 'MD', name: 'Moldova',               nationality: 'Moldovan' },
  { code: 'MC', name: 'Monaco',                nationality: 'Monégasque' },
  { code: 'MN', name: 'Mongolia',              nationality: 'Mongolian' },
  { code: 'ME', name: 'Montenegro',            nationality: 'Montenegrin' },
  { code: 'MM', name: 'Myanmar',               nationality: 'Burmese' },
  { code: 'NP', name: 'Nepal',                 nationality: 'Nepali' },
  { code: 'NL', name: 'Netherlands',           nationality: 'Dutch' },
  { code: 'NZ', name: 'New Zealand',           nationality: 'New Zealander' },
  { code: 'NI', name: 'Nicaragua',             nationality: 'Nicaraguan' },
  { code: 'NO', name: 'Norway',                nationality: 'Norwegian' },
  { code: 'OM', name: 'Oman',                  nationality: 'Omani' },
  { code: 'PK', name: 'Pakistan',              nationality: 'Pakistani' },
  { code: 'PA', name: 'Panama',                nationality: 'Panamanian' },
  { code: 'PG', name: 'Papua New Guinea',      nationality: 'Papua New Guinean' },
  { code: 'PY', name: 'Paraguay',              nationality: 'Paraguayan' },
  { code: 'PE', name: 'Peru',                  nationality: 'Peruvian' },
  { code: 'PH', name: 'Philippines',           nationality: 'Filipino' },
  { code: 'PL', name: 'Poland',                nationality: 'Polish' },
  { code: 'PT', name: 'Portugal',              nationality: 'Portuguese' },
  { code: 'QA', name: 'Qatar',                 nationality: 'Qatari' },
  { code: 'RO', name: 'Romania',               nationality: 'Romanian' },
  { code: 'RU', name: 'Russia',                nationality: 'Russian' },
  { code: 'KN', name: 'Saint Kitts & Nevis',   nationality: 'Kittitian' },
  { code: 'LC', name: 'Saint Lucia',           nationality: 'Saint Lucian' },
  { code: 'VC', name: 'Saint Vincent & the Grenadines', nationality: 'Vincentian' },
  { code: 'WS', name: 'Samoa',                 nationality: 'Samoan' },
  { code: 'SM', name: 'San Marino',            nationality: 'Sammarinese' },
  { code: 'SA', name: 'Saudi Arabia',          nationality: 'Saudi Arabian' },
  { code: 'RS', name: 'Serbia',                nationality: 'Serbian' },
  { code: 'SG', name: 'Singapore',             nationality: 'Singaporean' },
  { code: 'SK', name: 'Slovakia',              nationality: 'Slovak' },
  { code: 'SI', name: 'Slovenia',              nationality: 'Slovenian' },
  { code: 'SB', name: 'Solomon Islands',       nationality: 'Solomon Islander' },
  { code: 'ES', name: 'Spain',                 nationality: 'Spanish' },
  { code: 'LK', name: 'Sri Lanka',             nationality: 'Sri Lankan' },
  { code: 'SR', name: 'Suriname',              nationality: 'Surinamese' },
  { code: 'SE', name: 'Sweden',                nationality: 'Swedish' },
  { code: 'CH', name: 'Switzerland',           nationality: 'Swiss' },
  { code: 'SY', name: 'Syria',                 nationality: 'Syrian' },
  { code: 'TW', name: 'Taiwan',                nationality: 'Taiwanese' },
  { code: 'TJ', name: 'Tajikistan',            nationality: 'Tajikistani' },
  { code: 'TH', name: 'Thailand',              nationality: 'Thai' },
  { code: 'TL', name: 'Timor-Leste',           nationality: 'Timorese' },
  { code: 'TO', name: 'Tonga',                 nationality: 'Tongan' },
  { code: 'TT', name: 'Trinidad & Tobago',     nationality: 'Trinidadian' },
  { code: 'TR', name: 'Turkey',                nationality: 'Turkish' },
  { code: 'TM', name: 'Turkmenistan',          nationality: 'Turkmen' },
  { code: 'TV', name: 'Tuvalu',                nationality: 'Tuvaluan' },
  { code: 'UA', name: 'Ukraine',               nationality: 'Ukrainian' },
  { code: 'AE', name: 'United Arab Emirates',  nationality: 'Emirati' },
  { code: 'GB', name: 'United Kingdom',        nationality: 'British' },
  { code: 'US', name: 'United States',         nationality: 'American' },
  { code: 'UY', name: 'Uruguay',               nationality: 'Uruguayan' },
  { code: 'UZ', name: 'Uzbekistan',            nationality: 'Uzbekistani' },
  { code: 'VU', name: 'Vanuatu',               nationality: 'Ni-Vanuatu' },
  { code: 'VE', name: 'Venezuela',             nationality: 'Venezuelan' },
  { code: 'VN', name: 'Vietnam',               nationality: 'Vietnamese' },
  { code: 'YE', name: 'Yemen',                 nationality: 'Yemeni' },
]

// Deduplicate by code (Ghana appeared twice)
const seen = new Set<string>()
const deduped: Country[] = []
for (const c of COUNTRIES) {
  if (!seen.has(c.code)) {
    seen.add(c.code)
    deduped.push(c)
  }
}
export const ALL_COUNTRIES = deduped
